apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: chat-app
  labels:
    helm.sh/chart: chat-app-1.0.0
    app.kubernetes.io/name: chat-app
    app.kubernetes.io/managed-by: Helm
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "chatdb"
  DB_USER: "chatuser"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  SERVER_PORT: "8080"
