apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  DB_USER: {{ .Values.postgresql.auth.username | quote }}
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  SERVER_PORT: {{ .Values.config.server.port | quote }}
